# --------------------------可配置内容----------------------------

title: Tech Tip
email: zzygit@gmail.com
description: >- 
baseurl: ""
url: ""

# logo: "/assets/images/avatar.jpeg"


# 文章配置
defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true


# 个人信息配置
author:
  name     : "Zeyang Zhou"
  avatar   : "/assets/images/avatar.jpeg"
  bio      : "Share ."
  location : "Guangzhou, China"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=lxfooxYAAAAJ&hl=en&oi=sra"




# --------------------------固定配置----------------------------

minimal_mistakes_skin: "air"

locale: zh-CN

search : true

github: [metadata]

plugins:
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/ 
    
tag_archive: 
  type: liquid 
  path: /tags/

remote_theme: "mmistakes/minimal-mistakes"


