plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "scutzzy"
email: zzygit@gmail.com
description: ""
github:
  username: scutzzy
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: scutzzy.github.io
    client_id: c81df9b511e1408813b7
    client_secret: f9efc7ae41a09b94e306fd34cb32d8fc959594d8

url: "https://scutzzy.github.io"
imgrepo: "https://scutzzy.github.io/static/img"